spring:
  application:
    name: hunmuk

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hunmukdb
    username: sa

  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true
  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


hunmuk:
  jwt-key: "U2grUHZhL2JwZmpKSy9wSFlrbGxFdGMvMVkwNWVjNG02UDNmRHlDalhDMD0="

