### 게시글작성

POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "제목입니다.",
  "contents": "내용입니다."
}

### 게시글 삭제

DELETE http://localhost:8080/posts/2
Content-Type: application/json
